package br.com.visao;

import br.com.controller.Calculos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class MinhaCalculadora {
    private JPanel panel1; // esse é o painel raiz, confere o nome real no form
    private JTextField textValor1;
    private JTextField textValor2;
    private JLabel valor1;
    private JLabel valor2;
    private JLabel resultado;
    private JButton jBsomar;
    private JButton jBsubtracao;
    private JButton jBmultiplicar;
    private JButton jBdividir;

    public MinhaCalculadora() {
        jBsomar.addActionListener(this::jbsomarActionPerformed);
        jBsubtracao.addActionListener(this::jbsubtracaoActionPerformed);
        jBmultiplicar.addActionListener(this::jbmultiplicacaoActionPerformed);
        jBdividir.addActionListener(this::jbdivisaoActionPerformed);
    }

    private void jbsomarActionPerformed(ActionEvent evt) {
        Calculos c = new Calculos();
        c.setValor1(Double.valueOf(textValor1.getText()));
        c.setValor2(Double.valueOf(textValor2.getText()));
        c.setOp(1);
        resultado.setText("Soma =" + c.calcular());
    }

    private void jbsubtracaoActionPerformed(ActionEvent evt) {
        Calculos c = new Calculos();
        c.setValor1(Double.valueOf(textValor1.getText()));
        c.setValor2(Double.valueOf(textValor2.getText()));
        c.setOp(2);
        resultado.setText("Subtração =" + c.calcular());
    }

    private void jbmultiplicacaoActionPerformed(ActionEvent evt) {
        Calculos c = new Calculos();
        c.setValor1(Double.valueOf(textValor1.getText()));
        c.setValor2(Double.valueOf(textValor2.getText()));
        c.setOp(3);
        resultado.setText("Multiplicação =" + c.calcular());
    }

    private void jbdivisaoActionPerformed(ActionEvent evt) {
        Calculos c = new Calculos();
        c.setValor1(Double.valueOf(textValor1.getText()));
        c.setValor2(Double.valueOf(textValor2.getText()));
        c.setOp(4);
        if (c.getValor2() == 0) {
            resultado.setText("OPAI VEI NAO DA PRA DIVIDIR POR ZERO NE PIVETE, BARRIL DOBRADO");
        } else {
            resultado.setText("Divisão =" + c.calcular());
        }
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Minha Calculadora");
        frame.setContentPane(new MinhaCalculadora().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 5, new Insets(0, 0, 0, 0), -1, -1));
        valor1 = new JLabel();
        valor1.setText("Digite o valor 1");
        panel1.add(valor1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        valor2 = new JLabel();
        valor2.setText("Digite o valor 2");
        panel1.add(valor2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textValor1 = new JTextField();
        textValor1.setText("");
        panel1.add(textValor1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textValor2 = new JTextField();
        panel1.add(textValor2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        resultado = new JLabel();
        resultado.setText("0.00");
        panel1.add(resultado, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jBsomar = new JButton();
        jBsomar.setText("+");
        panel1.add(jBsomar, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jBsubtracao = new JButton();
        jBsubtracao.setText("-");
        panel1.add(jBsubtracao, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jBmultiplicar = new JButton();
        jBmultiplicar.setText("*");
        panel1.add(jBmultiplicar, new com.intellij.uiDesigner.core.GridConstraints(3, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jBdividir = new JButton();
        jBdividir.setText("/");
        panel1.add(jBdividir, new com.intellij.uiDesigner.core.GridConstraints(3, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}